export const EXPERTISE_LIST = [
  { id: 'it_technology', label: 'IT & Technology' },
  { id: 'finance_accounting', label: 'Finance & Accounting' },
  { id: 'marketing_communications', label: 'Marketing & Communications' },
  { id: 'sales_business', label: 'Sales & Business Development' },
  { id: 'hr_people', label: 'HR & People' },
  { id: 'operations_supply', label: 'Operations & Supply Chain' },
  { id: 'data_analytics', label: 'Data & Analytics' },
  { id: 'strategy_management', label: 'Strategy & Management' },
  { id: 'project_programme', label: 'Project & Programme Management' },
  { id: 'product_management', label: 'Product Management' },
  { id: 'customer_service', label: 'Customer Service & Support' },
  { id: 'legal_compliance', label: 'Legal & Compliance' },
  { id: 'admin_support', label: 'Administration & Office Support' },
  { id: 'procurement_purchasing', label: 'Procurement & Purchasing' },
  { id: 'logistics_transport', label: 'Logistics & Transport' },
  { id: 'engineering_manufacturing', label: 'Engineering & Manufacturing' },
  { id: 'creative_design', label: 'Creative, Design & Media' },
  { id: 'education_training', label: 'Education & Training' },
  { id: 'healthcare_social', label: 'Healthcare & Social Care' },
  { id: 'hospitality_tourism', label: 'Hospitality & Tourism' },
  { id: 'real_estate_property', label: 'Real Estate & Property' },
  { id: 'public_sector', label: 'Public Sector & Non-profit' },
];
