// Comprehensive flat expertise options (used in profile dropdowns)
export const EXPERTISE_OPTIONS = [
  'Accounting',
  'Actuarial',
  'Administration',
  'Advisor',
  'Aerodynamics',
  'Aeronautics',
  'Agribusiness',
  'Agriculture',
  'Animator',
  'Anthropology / Social Mediation',
  'Arboriculture',
  'Architecture',
  'Archivist',
  'Area',
  'Association',
  'Audit',
  'Bank',
  'Biochemistry',
  'Biology',
  'Brand',
  'Brokerage',
  'Building',
  'Business',
  'Buyer / Purchasing',
  'Call Center',
  'Care',
  'Carpentry',
  'Chemistry',
  'Clinical Research',
  'Communication',
  'Compliance',
  'Construction',
  'Consulting',
  'Content',
  'Contract',
  'Controlling',
  'Coordination',
  'Cosmetics',
  'Credit',
  'Customer Service',
  'Data Science / Analytics',
  'Decoration',
  'Delivery',
  'Demolition',
  'Design',
  'Development',
  'Dietetics / Nutrition',
  'Digital Marketing',
  'Distribution',
  'Documentation',
  'Drafting / Design Drafting',
  'Education',
  'Electrical',
  'Electronics',
  'Energy',
  'Engineering',
  'Environment',
  'Events',
  'Facilities',
  'Fashion',
  'Finance',
  'Fishing',
  'Food Industry',
  'Forestry',
  'Front Desk',
  'Geology / Geotechnics',
  'Health',
  'Healthcare',
  'Helpdesk / Support',
  'Hospitality',
  'Hotel',
  'HR / Human Resources',
  'Hydraulics / Hydrology',
  'Import Export',
  'Industrial Maintenance',
  'Industrial Process',
  'Infrastructure',
  'Insurance',
  'Interior Design',
  'Investigation',
  'IT / Information Systems',
  'Jewellery',
  'Journalism',
  'Key Account / Account Management',
  'Laboratory',
  'Landscape',
  'Law / Legal',
  'Learning',
  'Leasing / Rentals',
  'Leisure / Tourism Animation',
  'Litigation',
  'Logistics',
  'Luxury',
  'Machining',
  'Maintenance',
  'Manufacturing',
  'Marketing',
  'Materials',
  'Mechanics',
  'Medical',
  'Media',
  'Metrology',
  'NGO / Humanitarian',
  'Nuclear',
  'Nursing',
  'Office',
  'Oil and Gas',
  'Operations',
  'Optics / Optometry',
  'Organization',
  'Paper / Stationery',
  'Payroll',
  'Pharmaceutical',
  'Pharmacy',
  'Photography',
  'Planning',
  'Plastics',
  'Printing',
  'Production',
  'Project Management',
  'Psychology / Psychotherapy / Psychiatry',
  'Public Relations',
  'Quality',
  'Real Estate',
  'Reception',
  'Recycling',
  'Recruitment',
  'Regulatory',
  'Research and Development',
  'Restaurant / Catering',
  'Risk',
  'Road / Highways',
  'Safety / HSE / QHSE',
  'Sales',
  'Scheduling / Planning',
  'Science',
  'Secretarial / Assistance',
  'Security',
  'Services',
  'Shipping',
  'Social Services',
  'Social Support',
  'Software Development / Engineering',
  'Solar / Renewable Energy',
  'Sport',
  'Steel',
  'Supply Chain',
  'Tax',
  'Teaching / Training / Trainer',
  'Technical Support',
  'Telecom',
  'Textile',
  'Tourism',
  'Traffic',
  'Transport',
  'Urban Planning',
  'UX / UI',
  'Waste Management',
  'Water Management',
  'Wealth Management',
  'Web / Digital',
  'Other',
];

/**
 * Converts an EXPERTISE_OPTIONS label to the translation key used in
 * expertise_options.* — e.g. "HR / Human Resources" → "hr_human_resources"
 */
export function expertiseKey(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');
}

// Grouped expertise options used on the signup page
export const EXPERTISE_LIST = [
  { id: 'it_technology', label: 'IT & Technology' },
  { id: 'finance_accounting', label: 'Finance & Accounting' },
  { id: 'marketing_communications', label: 'Marketing & Communications' },
  { id: 'sales_business', label: 'Sales & Business Development' },
  { id: 'hr_people', label: 'HR & People' },
  { id: 'operations_supply', label: 'Operations & Supply Chain' },
  { id: 'data_analytics', label: 'Data & Analytics' },
  { id: 'strategy_management', label: 'Strategy & Management' },
  { id: 'project_programme', label: 'Project & Programme Management' },
  { id: 'product_management', label: 'Product Management' },
  { id: 'customer_service', label: 'Customer Service & Support' },
  { id: 'legal_compliance', label: 'Legal & Compliance' },
  { id: 'admin_support', label: 'Administration & Office Support' },
  { id: 'procurement_purchasing', label: 'Procurement & Purchasing' },
  { id: 'logistics_transport', label: 'Logistics & Transport' },
  { id: 'engineering_manufacturing', label: 'Engineering & Manufacturing' },
  { id: 'creative_design', label: 'Creative, Design & Media' },
  { id: 'education_training', label: 'Education & Training' },
  { id: 'healthcare_social', label: 'Healthcare & Social Care' },
  { id: 'hospitality_tourism', label: 'Hospitality & Tourism' },
  { id: 'real_estate_property', label: 'Real Estate & Property' },
  { id: 'public_sector', label: 'Public Sector & Non-profit' },
];
