/**
 * lib/frappe.ts
 *
 * Frappe HR / ERPNext REST API client for Jorbex payroll integration.
 *
 * Covers the full employee lifecycle:
 *   1. Create employee record
 *   2. Assign salary structure
 *   3. Generate salary slip (payslip)
 *   4. Fetch payslip data + PDF
 *   5. Disburse salary via Paystack Transfer
 *
 * Country support: Nigeria (PAYE, PENCOM, NHF, NSITF) + Kenya (PAYE, SHIF, NSSF, Housing Levy)
 *
 * Authentication: Token-based — Authorization: token api_key:api_secret
 * Base URL: https://{FRAPPE_HOST}/api/resource/{DocType}
 */

import axios, { AxiosInstance, isAxiosError } from 'axios';

// ─── Config ──────────────────────────────────────────────────────────────────

const FRAPPE_HOST    = process.env.FRAPPE_HOST    || '';   // e.g. https://payroll.jorbex.com
const FRAPPE_API_KEY = process.env.FRAPPE_API_KEY || '';
const FRAPPE_SECRET  = process.env.FRAPPE_API_SECRET || '';
const FRAPPE_COMPANY = process.env.FRAPPE_COMPANY || 'Jorbex';

// ─── Types ───────────────────────────────────────────────────────────────────

export type SupportedCountry = 'NG' | 'KE' | 'GH' | 'ZA' | 'UG' | 'TZ' | 'RW';

export interface FrappeEmployee {
  name?:            string;   // auto-generated by Frappe e.g. "HR-EMP-00001"
  employee_number?: string;   // your internal ID (Jorbex candidate ID)
  first_name:       string;
  last_name?:       string;
  date_of_birth:    string;   // YYYY-MM-DD
  gender:           'Male' | 'Female' | 'Other';
  date_of_joining:  string;   // YYYY-MM-DD
  company:          string;
  department?:      string;
  designation?:     string;
  employment_type?: string;
  personal_email?:  string;
  cell_number?:     string;
  country:          string;   // ISO2 e.g. NG, KE
  // Nigeria-specific
  pf_number?:       string;   // PENCOM pension fund account number
  tax_id?:          string;   // Nigeria TIN
  // Kenya-specific
  nhif_number?:     string;
  nssf_number?:     string;
  kra_pin?:         string;
}

export interface SalaryStructureAssignment {
  employee:          string;   // Frappe employee name
  salary_structure:  string;   // e.g. "Nigeria-Standard" or "Kenya-Standard"
  from_date:         string;   // YYYY-MM-DD
  base:              number;   // monthly gross salary (in local currency)
  currency:          string;   // ISO currency code e.g. NGN, KES
}

export interface SalarySlip {
  name:            string;   // Frappe slip ID e.g. "Salary Slip/00001"
  employee:        string;
  employee_name:   string;
  start_date:      string;
  end_date:        string;
  posting_date:    string;
  gross_pay:       number;
  total_deduction: number;
  net_pay:         number;
  currency:        string;
  earnings:        SalaryComponent[];
  deductions:      SalaryComponent[];
  docstatus:       0 | 1 | 2;  // 0=Draft, 1=Submitted, 2=Cancelled
}

export interface SalaryComponent {
  salary_component: string;   // e.g. "PAYE Tax", "PENCOM Pension"
  amount:           number;
}

export interface PayslipSummary {
  slipId:       string;
  employeeId:   string;
  employeeName: string;
  month:        string;   // "March 2026"
  grossPay:     number;
  netPay:       number;
  deductions:   number;
  currency:     string;
  pdfUrl?:      string;   // S3 URL after we store it
  components:   SalaryComponent[];
}

// ─── HTTP Client ─────────────────────────────────────────────────────────────

function getClient(): AxiosInstance {
  if (!FRAPPE_HOST || !FRAPPE_API_KEY || !FRAPPE_SECRET) {
    throw new Error('[Frappe] FRAPPE_HOST, FRAPPE_API_KEY, and FRAPPE_API_SECRET must be set');
  }
  return axios.create({
    baseURL: FRAPPE_HOST,
    headers: {
      Authorization: `token ${FRAPPE_API_KEY}:${FRAPPE_SECRET}`,
      'Content-Type': 'application/json',
    },
  });
}

// ─── 1. Employee Management ──────────────────────────────────────────────────

/**
 * Create a new employee record in Frappe HR.
 * Called when an offer is accepted and EOR onboarding is triggered.
 */
export async function createEmployee(data: FrappeEmployee): Promise<string> {
  const client = getClient();
  try {
    const res = await client.post('/api/resource/Employee', {
      ...data,
      company: data.company || FRAPPE_COMPANY,
      status: 'Active',
    });
    const employeeName: string = res.data?.data?.name;
    if (!employeeName) throw new Error('Employee created but no name returned');
    return employeeName;
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      console.error('[Frappe] createEmployee failed:', err.response?.data || err.message);
      throw new Error(err.response?.data?.exc_type || 'Failed to create employee in Frappe HR');
    }
    throw err;
  }
}

/**
 * Fetch an employee record by their Frappe employee name or employee_number.
 */
export async function getEmployee(frappeEmployeeName: string): Promise<FrappeEmployee> {
  const client = getClient();
  try {
    const res = await client.get(`/api/resource/Employee/${frappeEmployeeName}`);
    return res.data?.data;
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      throw new Error(err.response?.data?.exc_type || 'Failed to fetch employee');
    }
    throw err;
  }
}

/**
 * Update an employee record (e.g. on profile change).
 */
export async function updateEmployee(
  frappeEmployeeName: string,
  updates: Partial<FrappeEmployee>
): Promise<void> {
  const client = getClient();
  try {
    await client.put(`/api/resource/Employee/${frappeEmployeeName}`, updates);
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      throw new Error(err.response?.data?.exc_type || 'Failed to update employee');
    }
    throw err;
  }
}

// ─── 2. Salary Structure Assignment ─────────────────────────────────────────

/**
 * Assign a salary structure to an employee.
 * The salary structure must already exist in Frappe (created once during setup).
 * For Nigeria use "Nigeria-Standard", for Kenya use "Kenya-Standard".
 */
export async function assignSalaryStructure(data: SalaryStructureAssignment): Promise<void> {
  const client = getClient();
  try {
    await client.post('/api/resource/Salary Structure Assignment', {
      employee:         data.employee,
      salary_structure: data.salary_structure,
      from_date:        data.from_date,
      base:             data.base,
      currency:         data.currency,
      docstatus:        1,   // submit immediately
    });
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      console.error('[Frappe] assignSalaryStructure failed:', err.response?.data || err.message);
      throw new Error(err.response?.data?.exc_type || 'Failed to assign salary structure');
    }
    throw err;
  }
}

/**
 * Returns the correct salary structure name for a given country.
 * These structures must be configured once in your Frappe instance.
 */
export function getSalaryStructureName(country: SupportedCountry): string {
  const map: Record<SupportedCountry, string> = {
    NG: 'Nigeria-Standard',
    KE: 'Kenya-Standard',
    GH: 'Ghana-Standard',
    ZA: 'SouthAfrica-Standard',
    UG: 'Uganda-Standard',
    TZ: 'Tanzania-Standard',
    RW: 'Rwanda-Standard',
  };
  return map[country] ?? 'Africa-Basic';
}

// ─── 3. Salary Slip (Payslip) ────────────────────────────────────────────────

/**
 * Generate a salary slip for a single employee for a given month.
 * Creates in draft (docstatus=0), then submits (docstatus=1).
 * Returns the Frappe slip name e.g. "Salary Slip/00001".
 */
export async function generateSalarySlip(
  frappeEmployeeName: string,
  year: number,
  month: number   // 1-12
): Promise<string> {
  const client = getClient();
  const startDate = getMonthStart(year, month);
  const endDate   = getMonthEnd(year, month);

  try {
    // Step 1 — Create draft salary slip
    const createRes = await client.post('/api/resource/Salary Slip', {
      employee:   frappeEmployeeName,
      start_date: startDate,
      end_date:   endDate,
      docstatus:  0,
    });

    const slipName: string = createRes.data?.data?.name;
    if (!slipName) throw new Error('Salary slip created but no name returned');

    // Step 2 — Submit the slip (docstatus=1 triggers tax + deduction calculations)
    await client.put(`/api/resource/Salary Slip/${slipName}`, { docstatus: 1 });

    return slipName;
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      const errorBody = err.response?.data || err.message;
      console.error('[Frappe] generateSalarySlip failed:', errorBody);
      throw new Error(err.response?.data?.exc_type || 'Failed to generate salary slip');
    }
    throw err;
  }
}

/**
 * Generate a salary slip with custom Jorbex Office earnings (Hourly + OT).
 */
export async function generateSalarySlipWithEarnings(params: {
  frappeEmployeeName: string;
  year: number;
  month: number;
  earnings: SalaryComponent[];
}): Promise<string> {
  const client = getClient();
  const startDate = getMonthStart(params.year, params.month);
  const endDate   = getMonthEnd(params.year, params.month);

  try {
    // 1 — Create draft salary slip with injected earnings
    const createRes = await client.post('/api/resource/Salary Slip', {
      employee:   params.frappeEmployeeName,
      start_date: startDate,
      end_date:   endDate,
      docstatus:  0,
      earnings:   params.earnings, // Direct injection into the earnings table
    });

    const slipName = createRes.data?.data?.name;
    if (!slipName) throw new Error('Salary slip creation failed');

    // 2 — Submit the slip
    await client.put(`/api/resource/Salary Slip/${slipName}`, { docstatus: 1 });

    return slipName;
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      const errorBody = err.response?.data || err.message;
      console.error('[Frappe] generateSalarySlipWithEarnings failed:', errorBody);
      throw new Error(err.response?.data?.exc_type || 'Failed to generate hourly salary slip');
    }
    throw err;
  }
}

/**
 * Fetch a single salary slip by its Frappe name.
 */
export async function getSalarySlip(slipName: string): Promise<SalarySlip> {
  const client = getClient();
  try {
    const res = await client.get(`/api/resource/Salary Slip/${slipName}`);
    return res.data?.data;
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      throw new Error(err.response?.data?.exc_type || 'Failed to fetch salary slip');
    }
    throw err;
  }
}

/**
 * Fetch all salary slips for an employee.
 * Optionally filter by year/month.
 */
export async function getEmployeeSalarySlips(
  frappeEmployeeName: string,
  year?: number,
  month?: number
): Promise<SalarySlip[]> {
  const client = getClient();

  const filters: [string, string, string][] = [
    ['employee', '=', frappeEmployeeName],
    ['docstatus', '=', '1'],  // submitted only
  ];

  if (year && month) {
    filters.push(['start_date', '>=', getMonthStart(year, month)]);
    filters.push(['end_date',   '<=', getMonthEnd(year, month)]);
  }

  try {
    const res = await client.get('/api/resource/Salary Slip', {
      params: {
        filters: JSON.stringify(filters),
        fields:  JSON.stringify([
          'name', 'employee', 'employee_name',
          'start_date', 'end_date', 'posting_date',
          'gross_pay', 'total_deduction', 'net_pay', 'currency',
        ]),
        order_by: 'start_date desc',
        limit: 24,
      },
    });
    return res.data?.data ?? [];
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      throw new Error(err.response?.data?.exc_type || 'Failed to fetch salary slips');
    }
    throw err;
  }
}

/**
 * Download a salary slip as a PDF binary buffer.
 * Store this in S3 and return the URL for the candidate portal.
 */
export async function getSalarySlipPDF(slipName: string): Promise<Buffer> {
  const client = getClient();
  try {
    const res = await client.get('/api/method/frappe.utils.print_format.download_pdf', {
      params: {
        doctype:       'Salary Slip',
        name:          slipName,
        format:        'Standard',
        no_letterhead: 0,
      },
      responseType: 'arraybuffer',
    });
    return Buffer.from(res.data);
  } catch {
    throw new Error('Failed to download salary slip PDF');
  }
}

/**
 * Map a raw Frappe SalarySlip to a clean PayslipSummary for the Jorbex portal.
 */
export function mapToPayslipSummary(slip: SalarySlip, pdfUrl?: string): PayslipSummary {
  const date = new Date(slip.start_date);
  const month = date.toLocaleString('en-US', { month: 'long', year: 'numeric' });
  return {
    slipId:       slip.name,
    employeeId:   slip.employee,
    employeeName: slip.employee_name,
    month,
    grossPay:     slip.gross_pay,
    netPay:       slip.net_pay,
    deductions:   slip.total_deduction,
    currency:     slip.currency,
    pdfUrl,
    components:   [...(slip.earnings ?? []), ...(slip.deductions ?? [])],
  };
}

// ─── 4. Full Onboarding Flow (single call from API route) ───────────────────

/**
 * Onboard a new employee end-to-end:
 *   1. Create employee in Frappe HR
 *   2. Assign salary structure for their country
 *
 * Call this from /api/v1/eor/onboard when an offer is accepted cross-border.
 * Returns the Frappe employee name (e.g. "HR-EMP-00001") to store in EmploymentRecord.
 */
export async function onboardEmployee(params: {
  jorbexCandidateId: string;
  firstName:         string;
  lastName:          string;
  email:             string;
  phone?:            string;
  dateOfBirth:       string;   // YYYY-MM-DD
  gender:            'Male' | 'Female' | 'Other';
  startDate:         string;   // YYYY-MM-DD
  country:           SupportedCountry;
  grossMonthlySalary: number;
  currency:          string;
  designation?:      string;
  // Nigeria-specific
  taxId?:            string;
  pencomNumber?:     string;
  // Kenya-specific
  kraPin?:           string;
  nhifNumber?:       string;
  nssfNumber?:       string;
}): Promise<string> {
  // 1 — Create employee
  const frappeEmployeeName = await createEmployee({
    employee_number: params.jorbexCandidateId,
    first_name:      params.firstName,
    last_name:       params.lastName,
    personal_email:  params.email,
    cell_number:     params.phone,
    date_of_birth:   params.dateOfBirth,
    gender:          params.gender,
    date_of_joining: params.startDate,
    company:         FRAPPE_COMPANY,
    country:         params.country,
    designation:     params.designation,
    // Nigeria
    tax_id:          params.taxId,
    pf_number:       params.pencomNumber,
    // Kenya
    kra_pin:         params.kraPin,
    nhif_number:     params.nhifNumber,
    nssf_number:     params.nssfNumber,
  });

  // 2 — Assign salary structure
  await assignSalaryStructure({
    employee:         frappeEmployeeName,
    salary_structure: getSalaryStructureName(params.country),
    from_date:        params.startDate,
    base:             params.grossMonthlySalary,
    currency:         params.currency,
  });

  return frappeEmployeeName;
}

// ─── 5. Country Payroll Component Configs ────────────────────────────────────
//
// These define what salary components to configure in your Frappe instance
// during initial setup. Run setupCountryComponents() once after deployment.
// Each component maps to a Frappe "Salary Component" document.

export interface CountryPayrollConfig {
  country:     SupportedCountry;
  currency:    string;
  earnings:    ComponentConfig[];
  deductions:  ComponentConfig[];
}

interface ComponentConfig {
  name:        string;
  type:        'earning' | 'deduction';
  formula?:    string;   // Frappe formula (Python-like)
  amount?:     number;   // fixed amount
  description: string;
}

export const NIGERIA_PAYROLL_CONFIG: CountryPayrollConfig = {
  country:  'NG',
  currency: 'NGN',
  earnings: [
    { name: 'Basic Salary',         type: 'earning', description: 'Basic monthly salary' },
    { name: 'Housing Allowance',    type: 'earning', formula: 'base * 0.20', description: '20% of gross' },
    { name: 'Transport Allowance',  type: 'earning', formula: 'base * 0.10', description: '10% of gross' },
  ],
  deductions: [
    {
      name: 'PENCOM Pension',
      type: 'deduction',
      formula: '(base * 0.30) * 0.08',   // 8% of pensionable income (Basic + Housing + Transport = 30% rule)
      description: 'Employee pension contribution — 8% of pensionable income (PENCOM)',
    },
    {
      name: 'NHF',
      type: 'deduction',
      formula: '(base * 0.30) * 0.025',  // 2.5% of basic salary
      description: 'National Housing Fund — 2.5% of basic salary',
    },
    {
      name: 'NSITF',
      type: 'deduction',
      formula: 'base * 0.01',
      description: 'Nigeria Social Insurance Trust Fund — 1% of gross (employer-side, shown for record)',
    },
    {
      name: 'PAYE Tax',
      type: 'deduction',
      // PAYE is calculated using Frappe Income Tax Slab — configure the slab separately
      // Formula below is illustrative; actual slab-based calculation is done via
      // Frappe's Income Tax Slab feature (HR Settings > Income Tax Slab)
      formula: 'flt(annual_taxable_earning * 0.07 / 12)',
      description: 'Pay As You Earn — computed from Nigeria PAYE tax slab (configure in Income Tax Slab)',
    },
  ],
};

export const KENYA_PAYROLL_CONFIG: CountryPayrollConfig = {
  country:  'KE',
  currency: 'KES',
  earnings: [
    { name: 'Basic Pay',        type: 'earning', description: 'Basic monthly salary' },
    { name: 'House Allowance',  type: 'earning', formula: 'base * 0.15', description: '15% of gross' },
  ],
  deductions: [
    {
      name: 'SHIF',
      type: 'deduction',
      formula: 'max(base * 0.0275, 300)',  // 2.75% of gross, minimum KSh 300
      description: 'Social Health Insurance Fund (replaced NHIF Oct 2024) — 2.75% of gross',
    },
    {
      name: 'NSSF Tier I',
      type: 'deduction',
      formula: 'min(base * 0.06, 2160)',   // 6% up to KSh 2,160 (lower earnings limit)
      description: 'NSSF Tier I employee contribution',
    },
    {
      name: 'NSSF Tier II',
      type: 'deduction',
      formula: 'min(max(base - 6000, 0) * 0.06, 4320)', // 6% of earnings between Tier I and Tier II limit
      description: 'NSSF Tier II employee contribution',
    },
    {
      name: 'Housing Levy',
      type: 'deduction',
      formula: 'base * 0.015',
      description: 'Affordable Housing Levy — 1.5% of gross salary',
    },
    {
      name: 'PAYE Tax',
      type: 'deduction',
      formula: 'flt(annual_taxable_earning * 0.10 / 12)',
      description: 'Pay As You Earn — computed from Kenya KRA PAYE tax slab (configure in Income Tax Slab)',
    },
  ],
};

// ─── 6. Paystack Transfer (salary disbursement) ──────────────────────────────

/**
 * Disburse net salary to a candidate via Paystack Transfer API.
 * Called after a salary slip is submitted and confirmed.
 *
 * Paystack supports: bank transfers, M-Pesa (KE), MTN MoMo (GH, UG, RW), Airtel Money
 */
export async function disburseSalary(params: {
  recipientCode:  string;   // Paystack recipient code (stored on candidate profile)
  amountKobo:     number;   // amount in smallest currency unit (kobo for NGN, cents for KES)
  reference:      string;   // unique reference e.g. `payslip-${slipId}`
  reason:         string;   // e.g. "March 2026 salary — Jorbex"
}): Promise<string> {
  const PAYSTACK_SECRET = process.env.PAYSTACK_SECRET_KEY || '';
  if (!PAYSTACK_SECRET) throw new Error('[Frappe/Paystack] PAYSTACK_SECRET_KEY not set');

  try {
    const res = await axios.post(
      'https://api.paystack.co/transfer',
      {
        source:    'balance',
        amount:    params.amountKobo,
        recipient: params.recipientCode,
        reason:    params.reason,
        reference: params.reference,
      },
      {
        headers: {
          Authorization:  `Bearer ${PAYSTACK_SECRET}`,
          'Content-Type': 'application/json',
        },
      }
    );
    return res.data?.data?.transfer_code;
  } catch (err: unknown) {
    if (isAxiosError(err)) {
      console.error('[Frappe/Paystack] disburseSalary failed:', err.response?.data || err.message);
      throw new Error(err.response?.data?.message || 'Salary disbursement failed');
    }
    throw err;
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getMonthStart(year: number, month: number): string {
  return `${year}-${String(month).padStart(2, '0')}-01`;
}

function getMonthEnd(year: number, month: number): string {
  const lastDay = new Date(year, month, 0).getDate();
  return `${year}-${String(month).padStart(2, '0')}-${lastDay}`;
}
